FROM node:alpine

WORKDIR /usr/src/app

COPY package.json .

RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]

# 도커를 쓰므로 local 환경에 node_modules 파일 필요 없음, 또 node_modules가 로컬에 존재하면 COPY를 할때 node_modules까지 카피됨(어차피 컨테이너에는 npm install을 통해 node_modules가 생긴다.)
# Docker파일은 개발환경에서 쓰는 것과 운영환경에서 쓰는 것을 분리해주어야하는데 개발환경에서쓰이는 도커파일은 Dockerfile.dev이다.
# 개발환경의 도커파일을 이미지로 빌드 할때는 docker build -f Dockerfile.dev -t mnb9139/part6:latest . 와 같이 해주어야한다.
# 이미지를 컨테이너화할때는 docker run -p 3000:3000 -it mnb9139/part6:latest 와 같이 포트 매핑을 수행해주어야 한다.
# 리엑트에서 소스를 변경할 때마다 이미지를 빌드하는게 귀찮다면 docker volume을 이용하면 된다. 명령어는 다음과 같다.
# => (꼭 윈도우 파워셸에서 실행해야한다. && part6의 디렉터리로 이동할것) docker run -it -p 3000:3000 -v /usr/src/app/node_modules -v ${pwd}:/usr/src/app mnb9139/part6:latest
# 포트매핑과 볼륨매핑이 귀찮다면 docker-compose를 이용한다.
